import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Misa Clone',
  description: 'Generated by create next app',
  icons: {
    icon: 'https://www.misacdn.net/wp-content/uploads/2021/03/favicon.ico',
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
       <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" 
       rel="stylesheet" />
      </head>
      {/* <Link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/regular.min.css" rel="stylesheet" /> */}
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
